spring:
  application:
    name: greeting-service

greeting-service:
  greeting: "Olá"
  default-value: "Produção"

# allow show all endpoints in Actuator, see /actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"